### PR TITLE
Closes #44 adding enterprise parsing flags

### LINKED ISSUE #44: Feature Request: Enterprise style parsing
Enterprise customer here. The format that the metrics are being put in are not similar to how they were implemented for the enterprise influxdb handler. I had used a community handler prior to that but don't remember if there were differences there.

There are 2 differences with current format and the sensu enterprise influxdb handler. This is mostly for the graphite out metrics but could apply to any outputs.

1. Current: If the measurement has a '.' in the name, then the first word is used for the measurement name. The subsequent used as the key or the name of the value. Previously it was just "value", which is what the current process defaults to if there are no '.' to split.  After trying this out I saw no benefit when using grafana to display the data. I agree having something other then the generic "value" could add context but I saw no benefit when using grafana. Also, it would make queries more complicated to make, either static but much more if doing anything dynamic. 

Enterprise: The entire measurement is the measurement and the key for the value is always "value"

2. The tag was previously called host but now sensu_entity_name. Could add an additional 'host' tag but that would be a duplication and tags are indexed so doubling the index cost of inserting for no gain.   This is the least of the issues but still a pain to change everything to use sensu_entity_name (instead of 'host') and also it's really wordy and takes up more real-estate then is needed (IMHO)

I propose a -e --enterprise flag that will change this behavior.  I'm open to flag names of course.
I also refactored some of the code in the for loop I think it makes it cleaner and easy to test but again open to suggestions.

Thank you for your consideration on this feature request.

### PR DESCRIPTION
**Pull request by hurrycaine**
Signed-off-by: Hurrycaine <jason.e.joyner@gmail.com>

### CODE REVIEW

**Comment by hurrycaine** [comment]
There are no changes to functionality if the -e or --enterprise flags are not provided.  I did break out some of the logic in the for loop in func sendMetrics.  

The more conditionals we added the more that loop was getting harder to follow. I broke out each value into it's own function; setName, setTime, setFields and setTags. 
This will also allow fore easier testing. I did add some tests to ensure nothing broke and to test the functionality but did not touch any existing tests.

I avoided having a function do two things; the setName and setFields would be a good one to merge and return two values.  They both require a split of the measurement name and if it was combined the --host stripping could be put in there and would greatly simplify it's tests.

I also avoided changing the error handling but question on erroring immediately out on a bad timestamp. See func setTime. I think continuing the loop on an error would allowing indexing of all good measuments in a batch and then a total error could error out at the end of sendMetrics.

**Comment by nixwiz** [comment]
For the option, how about `-l` and `--legacy-format`?  Otherwise @jspaleta and I think it looks okay.

**Comment by hurrycaine** [comment]
I like legacy-format as well.  I updated the PR and because legacy-format (or enterprise) were not as self explanatory as --strip-host. I added more info to the readme.

**Comment by jspaleta** [comment]
hey!  thanks for the update on the PR.
I'm going to test these changes locally in my dev environment and look to get this merged next week.

I'm still looking to build up a github action env with running services to be able to add tests for changes like this as part of normal CI/CD. Just hitting a couple of snags with with github actions.

**Review by nixwiz — APPROVED** [review]
LGTM! 👍

**Pull request merged**
