### PR TITLE
Event annotations

### LINKED ISSUE #36: Add support for Sensu Enterprise-style annotations
The Sensu Enterprise integration for InfluxDB [supports two different modes for recording events](https://docs.sensu.io/sensu-enterprise/latest/integrations/influxdb/#overview) as timeseries data:

* Extract and record measurements when includes metric data
* When an event does not include metric data, multiple check attributes are recorded as an annotation on a measurement named `sensu_events`

The former is already implemented in this handler, but the latter is not. I ask that we implement the latter for increased parity with Sensu Enterprise capabilities.

### PR DESCRIPTION
**Pull request by nixwiz**
Closes #36 

Provide annotation point for 1.x parity.

Example of annotation with this Grafana Annotation definition:  `select description from sensu_event where $timeFilter ORDER BY time ASC`

Annotation

### CODE REVIEW

**Comment by calebhailey** [comment]
That was fast!!

**Comment by jspaleta** [comment]
lgtm

**Review by jspaleta — APPROVED** [review]

**Comment by jspaleta** [comment]
did a local build  and a test with system-profile-linux check.

Seems like its working.  There's some corner cases that need to be massaged
would definitely like to be able to optionally disable annotation 

example: the system-profile-linux asset is a basically just a big ole metrics check.
I'd like to run the influxdb handler without annotations as a metrics_handler for that check
but run influxdb handler with annotations as a status handler + incident filter to catch/annotate check failures

**Comment by sensu-discourse** [comment]
This pull request has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/pushing-check-results-to-influxdb/1793/14

**Pull request merged**
